site_name: Panduan Konfigurasi GitHub ke Terminal
site_description: Dokumentasi lengkap untuk mengkonfigurasi GitHub dengan terminal Linux
site_author: Salman Mustapa
site_url: https://salman-mustapa.github.io/github-setup

theme:
  name: material
  language: id
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Beranda: index.md
  - Persiapan:
      - Install Git: preparation/install-git.md
      - Membuat Akun GitHub: preparation/create-github-account.md
  - Konfigurasi:
      - Konfigurasi Dasar Git: configuration/basic-git-config.md
      - Setup Personal Access Token: configuration/setup-pat.md
      - Konfigurasi SSH (Opsional): configuration/setup-ssh.md
  - Testing & Verifikasi:
      - Test Koneksi: testing/test-connection.md
      - Operasi Git Dasar: testing/basic-git-operations.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md

repo_url: https://github.com/salman-mustapa/github-setup
repo_name: salman-mustapa/github-setup

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/salman-mustapa
    - icon: fontawesome/regular/envelope
      link: mailto:salmanmustapa@outlook.com
